### ISSUE TITLE
Statistiques

### ISSUE THREAD

**Issue by jonathanMelly** [jonathanMelly/pm2etml-intranet#24]
Les infos sont dans la db mais on en fait rien encore...

**Comment by BerSahli** [comment]
Valeur ajoutée 5 / 5

**Comment by jonathanMelly** [comment]
Renommée de Maître de classe : voit tous ses élèves !!! 

Séance de bulle du 08.05.2023
Évaluation: Chaque critère évalué (checkbox simple) ET choix des critères inclus ET ajustement des périodes comptables...
