### ISSUE TITLE
Petit bug avec la charge de travail (nombre de périodes)

### ISSUE THREAD

**Issue by GregLeBarbar** [jonathanMelly/pm2etml-intranet#33]
En effet, lorsque l'on édite notre projet/emploi, le nombre de périodes repasse à sa valeur par défaut (30 périodes) au lieu de nous proposer la valeur définie auparavant.

Type : Bug
Criticité : Faible

**Comment by jonathanMelly** [comment]
Déploiement en production programmé dans moins de 15 minutes #34
